# This is a basic workflow to help you get started with Actions

name: CIMain

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
     branches:
      - main
    # tags:
    #   - "v1*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0
      # - uses: wagoid/commitlint-github-action@v4
      
      - name: Use Node 
        uses: actions/setup-node@v1
        with:
          node-version: '20.9.0'
          #node-version: '16.10.0'
          #https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
      # Runs a set of commands using the runners shell
      - name: Run the build
        run: | 
          cd src
          ls
          cd blockly10
          npm i
          npm run build
          cd build
          ls -l
          # cd react_new_app
          # ls
          # cd blockly_automation
          # npm i 
          # npm run build
          # cd build 
          # ls -l          
          # cd src
          # cd AngWorkspace
          # npm i -g npm@8.3.0               
          # echo 'install angular'    
          # npm i  @angular/cli@13
          # # echo "install ws"
          # #npm i -force
          # #cd AutoBlocklyApp
          # #npm i
          # #cd ..
          # # echo "copy "
          # #cp -rn node_modules/  AutoBlocklyApp/          
          # #cp -rn node_modules/codemirror/  AutoBlocklyApp/codemirror          
          # # cp -rn node_modules/@types/codemirror/  AutoBlocklyApp/@types/codemirror
          # # ls -l AutoBlocklyApp/node_modules/codemirror
          # # echo "find"
          # #find . -type d -name "codemirror" -print
          # #npm install
          # cd projects
          # cd blockly-helpers
          # npm i
          # cd ..
          # cd blockly-scripts
          # npm i
          # cd ..
          # cd blockly-swagger
          # npm i
          # cd ..
          # cd ..
          # echo "build"
          # npm run buildGitHubPages  
          # ls -l dist/auto-blockly-app
          # npm run buildLibrary
          # ls -l dist/node2-blockly
          


