# This is a basic workflow to help you get started with Actions

name: CIPullRequest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: wagoid/commitlint-github-action@v4
      
      - name: Use Node 
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.0'
      # Runs a set of commands using the runners shell
      - name: Run the build
        run: |          
          cd src
          ls
          cd react_new_app
          ls
          cd blockly_automation
          npm i 
          npm run build
          cd build 
          ls -l          
          # cd src
          # npm i @angular/cli@13.0.1                      
          # npm i -ws --include-workspace-root --force           
          # cp -r node_modules  AutoBlocklyApp/node_modules
          # # ls -l AutoBlocklyApp/node_modules/*
          # npm run buildAng
          # ls -l AutoBlocklyApp/dist/AutoBlocklyApp
          # cd src
          # echo 'install angular'    
          # npm i  @angular/cli@12.2.13
          # echo "install ws"
          # npm i -ws --include-workspace-root 
          # ls -l node_modules/
          # echo "copy "
          # cp -r node_modules  AutoBlocklyApp/node_modules
          # echo 'lets see now the files'
          # ls -l AutoBlocklyApp/node_modules/
          # echo "build"
          # npm run buildAng
          # ls -l AutoBlocklyApp/dist/AutoBlocklyApp
          


